upstream_package_name: python-nitrate
downstream_package_name: python-nitrate

specfile_path: python-nitrate.spec
synced_files: [python-nitrate.spec]

actions:
  create-archive:
  - make tarball
  get-current-version:
  - make version

jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all
    - epel-8
    - epel-7
  trigger: pull_request
